### ISSUE TITLE
"animationDuration" styleable conflict

### ISSUE THREAD

**Issue by volvciklum** [nex3z/NotificationBadge#1]
"animationDuration" styleable may conflict with another one from different library. And it does in my case. Propose to rename all styleables to include some unique prefix for ex. "nb":
nbTextSize
nbTextColor
nbBackground
nbAnimationDuration
etc.

**Comment by nex3z** [comment]
Hi, volvciklum. Did you have the conflict with [material-intro-screen](https://github.com/TangoAgency/material-intro-screen)?
I tried NotificationBadge with [material-intro-screen](https://github.com/TangoAgency/material-intro-screen) and it complies (with buildToolsVersion “25.0.2”). I've found a 
```
<attr name="animationDuration" format="integer" />
```
 in [material-intro-screen](https://github.com/TangoAgency/material-intro-screen/blob/master/material-intro-screen/src/main/res/values/attrs.xml), which has the same format as in NotificationBadge. 

As per [this issue](https://code.google.com/p/android/issues/detail?id=22576) mentioned, it seems that build tools "24.0.1" fix this issue partially. When using libraries which contain attributes with the same name, if the attributes are in the same format, no compile error should occur. If the attributes are in different formats, there will be a "Attribute xxx already defined with incompatible format" error. 

Anyway I've prefixed the attribute in NotificationBadge to prevent any future conflict. Please find the new [README](https://github.com/nex3z/NotificationBadge/blob/master/README.md) and try
```
compile 'com.nex3z:notification-badge:0.2.0'
```

Thanks for the feedback.

**Comment by volvciklum** [comment]
Thanks a lot.

**Comment by volvciklum** [comment]
And yes, it was material-intro-screen.
