### ISSUE TITLE
How to save value of badge  into the sharedpreference ?

### ISSUE THREAD

**Issue by fazilmuammar** [nex3z/NotificationBadge#12]
i'm very confuse how to save value of badge into sharedpreference

**Comment by nex3z** [comment]
Save to SharedPreferences:

```java
SharedPreferences sharedPref = getPreferences(Context.MODE_PRIVATE);
SharedPreferences.Editor editor = sharedPref.edit();
editor.putInt("notification_num", 10);
editor.apply();
```

Restore from SharedPreferences:

```java
SharedPreferences sharedPref = getPreferences(Context.MODE_PRIVATE);
int number = sharedPref.getInt("notification_num", 0);
final NotificationBadge badge = findViewById(R.id.badge);
badge.setNumber(number);
```

**Comment by fazilmuammar** [comment]
Thank you for you answer sir, but how if i want to save value of badge with
button incerease. here my code sir:

private int mCount = 0;
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_home);
    Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
    setSupportActionBar(toolbar);
    getSupportActionBar().setTitle(null);
    BottomNavigationView navView = findViewById(R.id.nav_view);
    navView.setOnNavigationItemSelectedListener(mOnNavigationItemSelectedListener);
    final NotificationBadge badge = findViewById(R.id.badge);
    Button increase = findViewById(R.id.increase);
    increase.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            SharedPreferences sharedPreferencesTwo =
getSharedPreferences("one", MODE_PRIVATE);
            badge.setNumber(++ mCount);
            SharedPreferences.Editor editor = sharedPreferencesTwo.edit();
            editor.putString("content", String.valueOf(badge));
            editor.apply();

        }
    });

**Comment by nex3z** [comment]
You cannot save `badge` instance itself to SharedPreferences. Just save the value of `mCount` instead:

```java
SharedPreferences sharedPreferencesTwo =
getSharedPreferences("one", MODE_PRIVATE);
badge.setNumber(++ mCount);
SharedPreferences.Editor editor = sharedPreferencesTwo.edit();
editor.putInt("content", mCount);  // Save mCount
editor.apply()
```

**Comment by MustafaAndroid** [comment]
how to show store data in bage.setNumber(SharedPreferences.getCount()) using share SharedPreferences

**Comment by nex3z** [comment]
```java
SharedPreferences sharedPref = getPreferences(Context.MODE_PRIVATE);
int count = sharedPref.getInt("one", 0);
final NotificationBadge badge = findViewById(R.id.badge);
badge.setNumber(count);
```
