### ISSUE TITLE
change background colde

### ISSUE THREAD

**Issue by MustafaAndroid** [nex3z/NotificationBadge#13]
how can we change the color of background color through XML...??

**Comment by nex3z** [comment]
You can change the backgroud drawable with `nbBackground` attribute. 

The samples provides a basic red dot drawable. Add [this file](https://github.com/nex3z/NotificationBadge/blob/master/sample/src/main/res/drawable/badge_bg_with_shadow.xml) to your project and change [line 13](https://github.com/nex3z/NotificationBadge/blob/master/sample/src/main/res/drawable/badge_bg_with_shadow.xml#L13) to your desired color. Then assign it to `nbBackground`, like:

```xml
<com.nex3z.notificationbadge.NotificationBadge
    android:id="@+id/badge"
    android:layout_width="28dp"
    android:layout_height="28dp"
    app:nbBackground="@drawable/badge_bg_with_shadow"/>
```
