### ISSUE TITLE
Badge background image not visible

### ISSUE THREAD

**Issue by Eng-AhmedShehata** [nex3z/NotificationBadge#18]
After adding the 
``` xml
<com.nex3z.notificationbadge.NotificationBadge
    android:id="@+id/badge"
    android:layout_width="28dp"
    android:layout_height="28dp"
    app:nbMaxTextLength="2"/>
````
the whole badge not visible until I call:
setText(String text)
or
setNumber(int number)

**Comment by nex3z** [comment]
That's expected behaviour since there is nothing to show on the badge. If you just want to display an empty badge, you can use 

```
badge.setText(" ");
```

![device-2020-12-03-221823](https://user-images.githubusercontent.com/5645004/101034961-96c86400-35b5-11eb-93c2-1ba4f00a7cc5.png)

**Comment by Eng-AhmedShehata** [comment]
thank you but I recommend showing the icon if the there is no text to show.
