### ISSUE TITLE
setText() is ignoring MaxTextLength

### ISSUE THREAD

**Issue by ForestTree** [nex3z/NotificationBadge#2]
`setText()` is ignoring **MaxTextLength** when is going to show for first time. Probably problem in `setText()` method when **mIsBadgeShown** is false and full text will be shown, not ellipsized mBadgeText.

**Comment by nex3z** [comment]
Fixed in 54958e46e3e2f2ff33455d672b90b009e504c773. Please try 
```
compile 'com.nex3z:notification-badge:0.2.1
```

Thanks for the report!

**Comment by ForestTree** [comment]
Perfect! Thank you very much for quick response.
