### ISSUE TITLE
SHOW BADGES ON TAB LAYOUT

### ISSUE THREAD

**Issue by Gaetano-Dati** [nex3z/NotificationBadge#3]
Is it possible to link Badges to a TabLayout?  How to achieve this? Thanks

**Comment by nex3z** [comment]
You can use [`setCustomView()`](https://developer.android.com/reference/android/support/design/widget/TabLayout.Tab.html#setCustomView(android.view.View)) on [`TabLayout.Tab`](https://developer.android.com/reference/android/support/design/widget/TabLayout.Tab.html) to set custom tab.

I've added a sample [TabActivity.java](https://github.com/nex3z/NotificationBadge/blob/master/sample/src/main/java/com/nex3z/notificationbadge/sample/TabActivity.java).

![device-2018-01-22-204600](https://user-images.githubusercontent.com/5645004/35222987-d6f83eee-ffba-11e7-9cf1-f3833a00ad01.png)
