### ISSUE TITLE
nbBackground doesn't change its size

### ISSUE THREAD

**Issue by fauzynurn** [nex3z/NotificationBadge#8]
I have background like this : 

`<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="oval" >
            <solid android:color="@color/red"/>
            <size android:width="216dp"
                android:height="216dp" />
        </shape>
    </item>
</layer-list>`

This is my Notification Badge : 
`<com.nex3z.notificationbadge.NotificationBadge
            android:layout_width="216dp"
            android:layout_height="216dp"
            app:nbBackground="@drawable/circle_badge_bg"
            android:textSize="2sp"
            />`

No matter how much the background's width and height is, the size doesn't change.

**Comment by nex3z** [comment]
If you would like `NotificationBadge` to fit its background size, you need to set `NotificationBadge`'s `android:layout_width` and `android:layout_height` to `wrap_content`. 

```xml
<com.nex3z.notificationbadge.NotificationBadge
    android:id="@+id/badge"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:nbBackground="@drawable/circle_badge_bg"
    android:textSize="2sp" />
```
