### ISSUE TITLE
Notification Badge installation in VB 2017 failed

### ISSUE THREAD

**Issue by gurwin** [nex3z/NotificationBadge#9]
Hello everyone I am new with Visual basic am trying to solve this error from last two days but i didn't get any solution.Can somebody please guide me.
![capture](https://user-images.githubusercontent.com/40004944/41060757-92471894-699e-11e8-8837-e6cc98588125.PNG)

**Comment by nex3z** [comment]
Are you trying to build Android app with Visual Basic? I'm not familiar with this use case neither. Maybe you can get more help in Visual Basic community.

**Comment by gurwin** [comment]
Hey @nex3z 
Thanks for your reply,actually i am looking for the solution of notification badge on app icon and I am developing a cross-platform xamarin based application, but i didn't find any appropriate solution. Could you please suggest me any solution if you know.

**Comment by nex3z** [comment]
Looks like Xamarin is complaining `NotificationBadge` is not compatible with Android 8.1. Currently `NotificationBadge` is targeting Android 8.0, which shouldn't have problem supporting Android 8.1. Maybe Xamarin is more strict on version compatibility.

I've build a new version of `NotificationBadge` targeting Android 8.1. You can try the `v1.0.3` version.

```
implementation 'com.nex3z:notification-badge:1.0.3'
```
